name: github-actions
run-name: Execute Java Spring Boot Project
on:
  push:
    branches:
      [ main ]
  pull_request:
    branches:
      [ main ]
jobs:
  run-spring-boot-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: ./gradlew build